name: Validate

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [check_spec]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Validate Changes
      run: >
        docker build -t ohpc.${{ matrix.target }} -f tests/ci/Dockerfile.${{ matrix.target }} --build-arg COMMIT_RANGE="${{ github.event.pull_request.base.sha }}.." .
